### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by maddavo** [Maschell/libutils#2]
I am trying to compile libutils so that I can compile the homebrew for WiiU.  I have successfully installed DevkitPro on Windows and compiled dynamic_libs OK.  The libdynamic_libs.a is now in the portlibs/ppc/lib folder.
When I try 'make && make install' I get a whole lot of errors starting with sd_fat_devoptab.cpp .  How to compile??

full make errors follows:

`$ make && make install
sd_fat_devoptab.cpp
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp: In function 'sd_fat_private_t* sd_fat_get_device_data(const char*)':
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:69:11: error: 'devoptab_t' does not name a type; did you mean 'dev_t'?
     const devoptab_t *devoptab = NULL;
           ^~~~~~~~~~
           dev_t
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:81:21: error: 'STD_MAX' was not declared in this scope
     for (i = 3; i < STD_MAX; i++) {
                     ^~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:81:21: note: suggested alternative: 'SBT_MAX'
     for (i = 3; i < STD_MAX; i++) {
                     ^~~~~~~
                     SBT_MAX
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:82:9: error: 'devoptab' was not declared in this scope
         devoptab = devoptab_list[i];
         ^~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:82:9: note: suggested alternative: 'dev_t'
         devoptab = devoptab_list[i];
         ^~~~~~~~
         dev_t
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:82:20: error: 'devoptab_list' was not declared in this scope
         devoptab = devoptab_list[i];
                    ^~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:82:20: note: suggested alternative: 'va_list'
         devoptab = devoptab_list[i];
                    ^~~~~~~~~~~~~
                    va_list
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp: At global scope:
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:669:8: error: 'DIR_ITER' does not name a type; did you mean 'SI_TIMER'?
 static DIR_ITER *sd_fat_diropen_r (struct _reent *r, DIR_ITER *dirState, const char *path) {
        ^~~~~~~~
        SI_TIMER
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:706:49: error: 'DIR_ITER' has not been declared
 static int sd_fat_dirclose_r (struct _reent *r, DIR_ITER *dirState) {
                                                 ^~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp: In function 'int sd_fat_dirclose_r(_reent*, int*)':
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:707:67: error: request for member 'dirStruct' in '* dirState', which is of non-class type 'int'
     sd_fat_dir_entry_t *dirIter = (sd_fat_dir_entry_t *)dirState->dirStruct;
                                                                   ^~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp: At global scope:
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:726:49: error: 'DIR_ITER' has not been declared
 static int sd_fat_dirreset_r (struct _reent *r, DIR_ITER *dirState) {
                                                 ^~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp: In function 'int sd_fat_dirreset_r(_reent*, int*)':
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:727:67: error: request for member 'dirStruct' in '* dirState', which is of non-class type 'int'
     sd_fat_dir_entry_t *dirIter = (sd_fat_dir_entry_t *)dirState->dirStruct;
                                                                   ^~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp: At global scope:
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:746:48: error: 'DIR_ITER' has not been declared
 static int sd_fat_dirnext_r (struct _reent *r, DIR_ITER *dirState, char *filename, struct stat *st) {
                                                ^~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp: In function 'int sd_fat_dirnext_r(_reent*, int*, char*, stat*)':
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:747:67: error: request for member 'dirStruct' in '* dirState', which is of non-class type 'int'
     sd_fat_dir_entry_t *dirIter = (sd_fat_dir_entry_t *)dirState->dirStruct;
                                                                   ^~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp: At global scope:
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:789:14: error: 'devoptab_t' does not name a type; did you mean 'dev_t'?
 static const devoptab_t devops_sd_fat = {
              ^~~~~~~~~~
              dev_t
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp: In function 'int sd_fat_add_device(const char*, const char*, void*, void*)':
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:820:5: error: 'devoptab_t' was not declared in this scope
     devoptab_t *dev = NULL;
     ^~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:820:5: note: suggested alternative: 'dev_t'
     devoptab_t *dev = NULL;
     ^~~~~~~~~~
     dev_t
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:820:17: error: 'dev' was not declared in this scope
     devoptab_t *dev = NULL;
                 ^~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:820:17: note: suggested alternative: 'div'
     devoptab_t *dev = NULL;
                 ^~~
                 div
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:832:24: error: expected primary-expression before ')' token
     dev = (devoptab_t *) malloc(sizeof(devoptab_t) + strlen(name) + 1);
                        ^
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:875:18: error: 'devops_sd_fat' was not declared in this scope
     memcpy(dev, &devops_sd_fat, sizeof(devoptab_t));
                  ^~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:875:18: note: suggested alternative: 'unmount_sd_fat'
     memcpy(dev, &devops_sd_fat, sizeof(devoptab_t));
                  ^~~~~~~~~~~~~
                  unmount_sd_fat
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:880:21: error: 'STD_MAX' was not declared in this scope
     for (i = 3; i < STD_MAX; i++) {
                     ^~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:880:21: note: suggested alternative: 'SBT_MAX'
     for (i = 3; i < STD_MAX; i++) {
                     ^~~~~~~
                     SBT_MAX
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:881:13: error: 'devoptab_list' was not declared in this scope
         if (devoptab_list[i] == devoptab_list[0]) {
             ^~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:881:13: note: suggested alternative: 'va_list'
         if (devoptab_list[i] == devoptab_list[0]) {
             ^~~~~~~~~~~~~
             va_list
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp: In function 'void deleteDevTabsNames()':
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:904:11: error: 'devoptab_t' does not name a type; did you mean 'dev_t'?
     const devoptab_t * devoptab = NULL;
           ^~~~~~~~~~
           dev_t
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:905:28: error: 'devoptab_list' was not declared in this scope
     u32 last_entry = (u32) devoptab_list[STD_MAX-1];
                            ^~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:905:28: note: suggested alternative: 'va_list'
     u32 last_entry = (u32) devoptab_list[STD_MAX-1];
                            ^~~~~~~~~~~~~
                            va_list
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:905:42: error: 'STD_MAX' was not declared in this scope
     u32 last_entry = (u32) devoptab_list[STD_MAX-1];
                                          ^~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:905:42: note: suggested alternative: 'SBT_MAX'
     u32 last_entry = (u32) devoptab_list[STD_MAX-1];
                                          ^~~~~~~
                                          SBT_MAX
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:907:9: error: 'devoptab' was not declared in this scope
         devoptab = devoptab_list[i];
         ^~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:907:9: note: suggested alternative: 'dev_t'
         devoptab = devoptab_list[i];
         ^~~~~~~~
         dev_t
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:912:43: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
                 devoptab_list[i] = (const devoptab_t *)last_entry;
                                           ^~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:912:37: error: expected primary-expression before 'const'
                 devoptab_list[i] = (const devoptab_t *)last_entry;
                                     ^~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:912:37: error: expected ')' before 'const'
                 devoptab_list[i] = (const devoptab_t *)last_entry;
                                    ~^~~~~
                                     )
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp: In function 'int sd_fat_remove_device(const char*, void**, void**, char**)':
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:920:11: error: 'devoptab_t' does not name a type; did you mean 'dev_t'?
     const devoptab_t *devoptab = NULL;
           ^~~~~~~~~~
           dev_t
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:932:21: error: 'STD_MAX' was not declared in this scope
     for (i = 3; i < STD_MAX; i++) {
                     ^~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:932:21: note: suggested alternative: 'SBT_MAX'
     for (i = 3; i < STD_MAX; i++) {
                     ^~~~~~~
                     SBT_MAX
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:933:9: error: 'devoptab' was not declared in this scope
         devoptab = devoptab_list[i];
         ^~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:933:9: note: suggested alternative: 'dev_t'
         devoptab = devoptab_list[i];
         ^~~~~~~~
         dev_t
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:933:20: error: 'devoptab_list' was not declared in this scope
         devoptab = devoptab_list[i];
                    ^~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:933:20: note: suggested alternative: 'va_list'
         devoptab = devoptab_list[i];
                    ^~~~~~~~~~~~~
                    va_list
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:952:23: error: 'devoptab_t' was not declared in this scope
                 free((devoptab_t*)devoptab);
                       ^~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:952:23: note: suggested alternative: 'dev_t'
                 free((devoptab_t*)devoptab);
                       ^~~~~~~~~~
                       dev_t
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:952:34: error: expected primary-expression before ')' token
                 free((devoptab_t*)devoptab);
                                  ^
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp: At global scope:
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:746:12: warning: 'int sd_fat_dirnext_r(_reent*, int*, char*, stat*)' defined but not used [-Wunused-function]
 static int sd_fat_dirnext_r (struct _reent *r, DIR_ITER *dirState, char *filename, struct stat *st) {
            ^~~~~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:726:12: warning: 'int sd_fat_dirreset_r(_reent*, int*)' defined but not used [-Wunused-function]
 static int sd_fat_dirreset_r (struct _reent *r, DIR_ITER *dirState) {
            ^~~~~~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:706:12: warning: 'int sd_fat_dirclose_r(_reent*, int*)' defined but not used [-Wunused-function]
 static int sd_fat_dirclose_r (struct _reent *r, DIR_ITER *dirState) {
            ^~~~~~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:606:12: warning: 'int sd_fat_statvfs_r(_reent*, const char*, statvfs*)' defined but not used [-Wunused-function]
 static int sd_fat_statvfs_r (struct _reent *r, const char *path, struct statvfs *buf) {
            ^~~~~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:576:12: warning: 'int sd_fat_mkdir_r(_reent*, const char*, int)' defined but not used [-Wunused-function]
 static int sd_fat_mkdir_r (struct _reent *r, const char *path, int mode) {
            ^~~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:537:12: warning: 'int sd_fat_rename_r(_reent*, const char*, const char*)' defined but not used [-Wunused-function]
 static int sd_fat_rename_r (struct _reent *r, const char *oldName, const char *newName) {
            ^~~~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:507:12: warning: 'int sd_fat_chdir_r(_reent*, const char*)' defined but not used [-Wunused-function]
 static int sd_fat_chdir_r (struct _reent *r, const char *name) {
            ^~~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:476:12: warning: 'int sd_fat_unlink_r(_reent*, const char*)' defined but not used [-Wunused-function]
 static int sd_fat_unlink_r (struct _reent *r, const char *name) {
            ^~~~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:471:12: warning: 'int sd_fat_link_r(_reent*, const char*, const char*)' defined but not used [-Wunused-function]
 static int sd_fat_link_r (struct _reent *r, const char *existing, const char *newLink) {
            ^~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:421:12: warning: 'int sd_fat_stat_r(_reent*, const char*, stat*)' defined but not used [-Wunused-function]
 static int sd_fat_stat_r (struct _reent *r, const char *path, struct stat *st) {
            ^~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:400:12: warning: 'int sd_fat_fsync_r(_reent*, void*)' defined but not used [-Wunused-function]
 static int sd_fat_fsync_r (struct _reent *r, void* fd) {
            ^~~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:379:12: warning: 'int sd_fat_ftruncate_r(_reent*, void*, off_t)' defined but not used [-Wunused-function]
 static int sd_fat_ftruncate_r (struct _reent *r, void* fd, off_t len) {
            ^~~~~~~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:342:12: warning: 'int sd_fat_fstat_r(_reent*, void*, stat*)' defined but not used [-Wunused-function]
 static int sd_fat_fstat_r (struct _reent *r, void* fd, struct stat *st) {
            ^~~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:291:16: warning: 'ssize_t sd_fat_read_r(_reent*, void*, char*, size_t)' defined but not used [-Wunused-function]
 static ssize_t sd_fat_read_r (struct _reent *r, void* fd, char *ptr, size_t len) {
                ^~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:241:16: warning: 'ssize_t sd_fat_write_r(_reent*, void*, const char*, size_t)' defined but not used [-Wunused-function]
 static ssize_t sd_fat_write_r (struct _reent *r, void *fd, const char *ptr, size_t len) {
                ^~~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:206:14: warning: 'off_t sd_fat_seek_r(_reent*, void*, off_t, int)' defined but not used [-Wunused-function]
 static off_t sd_fat_seek_r (struct _reent *r, void* fd, off_t pos, int dir) {
              ^~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:186:12: warning: 'int sd_fat_close_r(_reent*, void*)' defined but not used [-Wunused-function]
 static int sd_fat_close_r (struct _reent *r, void *fd) {
            ^~~~~~~~~~~~~~
C:/Users/Dave/Downloads/Homebrew/libutils/source/fs/sd_fat_devoptab.cpp:114:12: warning: 'int sd_fat_open_r(_reent*, void*, const char*, int, int)' defined but not used [-Wunused-function]
 static int sd_fat_open_r (struct _reent *r, void *fileStruct, const char *path, int flags, int mode) {
            ^~~~~~~~~~~~~
make[1]: *** [/c/devkitpro/devkitPPC/base_rules:13: sd_fat_devoptab.o] Error 1
make: *** [Makefile:107: release] Error 2
`

**Comment by maddavo** [comment]
(unfortunately newlines didn't come through in the error output, but hopefully you get the idea)

**Comment by Maschell** [comment]
Which devkitPPC version are you using? I never tested the newest one (r32) which came out a few days ago. But Im going to take a look at it.

**Comment by Maschell** [comment]
Fixed with commit 177cb9b.
